#
# Autogenerated by Thrift Compiler (0.11.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

# 结构体定义
class Article
  include ::Thrift::Struct, ::Thrift::Struct_Union
  ID = 1
  TITLE = 2
  CONTENT = 3
  AUTHOR = 4

  FIELDS = {
    ID => {:type => ::Thrift::Types::I32, :name => 'id'},
    TITLE => {:type => ::Thrift::Types::STRING, :name => 'title'},
    CONTENT => {:type => ::Thrift::Types::STRING, :name => 'content'},
    AUTHOR => {:type => ::Thrift::Types::STRING, :name => 'author'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

